DEBUG = True
uri = 'postgres://postgres:11986143@127.0.0.1:5432/project0'
SQLALCHEMY_DATABASE_URI = uri
SECRET_KEY = 'Thisisasecret!'
SQLALCHEMY_TRACK_MODIFICATIONS = False
TEMPLATES_AUTO_RELOAD = True
SESSION_PERMANENT = False
SQLALCHEMY_ECHO = True
